# 6. 실습

In [146]:
# numpy import하기
import numpy as np

## 6-1. NumPy 배열 생성

In [147]:
# np.array()로 1차원 배열 [1, 2, 3, 4, 5] 생성 후 출력하기
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [148]:
# 1차원 배열의 데이터타입, 모양, 배열 전체 element의 수, 차원의 수 출력하기
arr.dtype, arr.shape, len(arr), arr.ndim

(dtype('int64'), (5,), 5, 1)

In [149]:
# np.array()로 아래 2차원 배열 생성 후 출력하기
# [[10, 20, 30, 40],
#  [50, 60, 70, 80]]
np.array([[10, 20, 30, 40],
 [50, 60, 70, 80]])

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [150]:
# np.arange()로 1차원 배열 [1, 2, 3, 4, 5] 생성 후 출력하기
np.arange(1, 6)

array([1, 2, 3, 4, 5])

In [151]:
# np.arange()로 아래 2차원 배열 생성 후 출력하기
# [[10, 20, 30, 40],
#  [50, 60, 70, 80]]
np.arange(10, 81, 10).reshape(2, 4)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [152]:
# 주사위를 100번 던져서 나오는 숫자 배열 출력하기
np.random.randint(1, 7, size=100)

array([1, 2, 1, 6, 5, 3, 1, 1, 3, 6, 3, 2, 1, 6, 3, 2, 6, 5, 3, 1, 4, 4,
       4, 6, 1, 6, 2, 5, 3, 4, 4, 5, 3, 5, 4, 2, 1, 5, 4, 5, 6, 3, 3, 5,
       3, 6, 5, 2, 3, 3, 1, 3, 3, 4, 6, 5, 3, 5, 4, 6, 2, 1, 1, 6, 2, 6,
       3, 5, 3, 4, 4, 2, 3, 4, 1, 2, 6, 6, 2, 6, 4, 1, 5, 3, 6, 5, 4, 5,
       5, 3, 1, 2, 1, 5, 6, 3, 6, 5, 5, 6])

In [153]:
# np.random을 사용하여 랜덤 실수값으로 이루어진 (3, 4) 2차원 배열 생성
np.random.random(size=(3,4))

array([[0.88001849, 0.27454204, 0.22458118, 0.81397318],
       [0.05820075, 0.73015342, 0.03267909, 0.59998723],
       [0.03054111, 0.85960489, 0.43977952, 0.56044466]])

## 6-2. 산술연산

In [154]:
# [1, 2, 3, 4, 5], [6, 7, 8, 9, 10] 1차원 배열 2개를 생성하고 출력하기
bread = np.arange(1, 6)
jam = np.arange(6, 11)
bread, jam

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [155]:
# 1차원 배열간 산술연산(덧셈, 뺄셈, 곱셈, 나눗셈) 하기
bread + jam, bread - jam, bread * jam, bread / jam

(array([ 7,  9, 11, 13, 15]),
 array([-5, -5, -5, -5, -5]),
 array([ 6, 14, 24, 36, 50]),
 array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ]))

In [156]:
# [[1, 2, 3, 4, 5]   [[11, 12, 13, 14, 15]
#  [6, 7, 8, 9, 10]], [16, 17, 18, 19, 20]] 2차원 배열 2개를 생성하고 출력하기
bam = np.arange(1, 11).reshape(2, 5)
bim = np.arange(11, 21).reshape(2, 5)
bam, bim

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]))

In [157]:
# 2차원 배열간 산술연산(덧셈, 뺄셈, 나눗셈) 하기
bam + bim, bam - bim, bam / bim

(array([[12, 14, 16, 18, 20],
        [22, 24, 26, 28, 30]]),
 array([[-10, -10, -10, -10, -10],
        [-10, -10, -10, -10, -10]]),
 array([[0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333],
        [0.375     , 0.41176471, 0.44444444, 0.47368421, 0.5       ]]))

In [158]:
# 두번째 배열의 shape을 (5, 2)로 만들고 출력하기
bim.shape = (5, 2)
bim

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [159]:
# 행렬곱셈(dot product) 연산하기
np.dot(tdarr1, tdarr2)

array([[245, 260],
       [620, 660]])

## 6-3. Aggregation 함수

In [184]:
# 1~10까지 이루어진 1차원 배열 생성하기
bob = np.arange(1, 11)
bob

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [161]:
# 최대값, 최소값 출력하기
np.max(bob), np.min(bob)

(10, 1)

In [162]:
# 배열요소의 합, 평균값 출력하기
np.sum(bob), np.mean(bob)

(55, 5.5)

In [163]:
# 중앙값(중위값), 표준편차 출력하기
np.median(bob), np.std(bob)

(5.5, 2.8722813232690143)

In [185]:
# 1~20까지 이루어진 2차원 배열 (4, 5) 생성하기
chicken = np.arange(1, 21).reshape(4, 5)
chicken

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [165]:
# 각 행의 max값, min값 출력하기
np.max(chicken, axis=1), np.min(chicken, axis=1)

(array([ 5, 10, 15, 20]), array([ 1,  6, 11, 16]))

In [166]:
# 각 열의 max값, min값 출력하기
np.max(chicken, axis=0), np.min(chicken, axis=0)

(array([16, 17, 18, 19, 20]), array([1, 2, 3, 4, 5]))

In [167]:
# 각 행의 sum값 출력하기
np.sum(chicken, axis=1)

array([15, 40, 65, 90])

In [168]:
# 각 열의 sum값 출력하기
np.sum(chicken, axis=0)

array([34, 38, 42, 46, 50])

## 6-4. 정렬

In [186]:
# 1~100까지 랜덤 정수값을 갖는 1차원 배열 (10, ) 생성하기
# seed값 100부여하기
np.random.seed(100)
palm = np.random.randint(1, 101, size=(10,))
palm

array([ 9, 25, 68, 88, 80, 49, 11, 95, 53, 99])

In [170]:
# 위 1차원 배열을 오름차순 정렬하기
ordered = np.sort(palm)
ordered

array([ 9, 11, 25, 49, 53, 68, 80, 88, 95, 99])

In [171]:
# 위 1차원 배열을 내림차순 정렬하기
ordered[::-1]

array([99, 95, 88, 80, 68, 53, 49, 25, 11,  9])

In [187]:
# 랜덤 seed값 100부여하기
# 1~100까지 랜덤 정수값을 갖는 2차원 배열 (5, 10) 생성하기
np.random.seed(100)
xlxlxlxlxl = np.random.randint(1, 101, size=(5, 10))
xlxlxlxlxl

array([[ 9, 25, 68, 88, 80, 49, 11, 95, 53, 99],
       [54, 67, 99, 15, 35, 25, 16, 61, 59, 17],
       [10, 94, 87,  3, 28,  5, 32,  2, 14, 84],
       [ 5, 92, 60, 68,  8, 50, 48, 66, 62, 15],
       [56, 72, 81,  3, 95, 20, 99, 64, 54, 28]])

In [173]:
# 열 기준 정렬하기
np.sort(xlxlxlxlxl, axis=0)

array([[ 5, 25, 60,  3,  8,  5, 11,  2, 14, 15],
       [ 9, 67, 68,  3, 28, 20, 16, 61, 53, 17],
       [10, 72, 81, 15, 35, 25, 32, 64, 54, 28],
       [54, 92, 87, 68, 80, 49, 48, 66, 59, 84],
       [56, 94, 99, 88, 95, 50, 99, 95, 62, 99]])

In [174]:
# 행 기준 정렬하기
np.sort(xlxlxlxlxl)

array([[ 9, 11, 25, 49, 53, 68, 80, 88, 95, 99],
       [15, 16, 17, 25, 35, 54, 59, 61, 67, 99],
       [ 2,  3,  5, 10, 14, 28, 32, 84, 87, 94],
       [ 5,  8, 15, 48, 50, 60, 62, 66, 68, 92],
       [ 3, 20, 28, 54, 56, 64, 72, 81, 95, 99]])

## 6-5. 인덱싱과 슬라이싱

In [175]:
# 0~14로 이루어진 2차원 배열 (3, 5) 생성하기
pizza = np.arange(0, 15).reshape(3, 5)
pizza

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [176]:
# 위 배열에서 7을 인덱싱하기
pizza[1, 2]

7

In [177]:
# 위 배열에서 14를 인덱싱하기 (음수 인덱스 사용)
pizza[-1, -1]

14

In [178]:
# 위 배열에서 배열 [6, 7]을 슬라이싱하기
pizza[1, 1:3]

array([6, 7])

In [179]:
# 위 배열에서 배열 [7, 12]을 슬라이싱하기
pizza[1:3, 2]

array([ 7, 12])

In [180]:
# 위 배열에서 [[3, 4], [8, 9]]을 슬라이싱하기
pizza[:2, 3:5]

array([[3, 4],
       [8, 9]])

In [181]:
# 위 배열에서 3의 배수 찾기
pizza[pizza % 3 ==0]

array([ 0,  3,  6,  9, 12])

In [182]:
# 위 배열에서 4로 나누면 1이 남는 수 찾기
pizza[pizza % 4 ==1]

array([ 1,  5,  9, 13])

In [183]:
# 위 배열에서 3의 배수이면서 4로 나누면 1이 남는 수 찾기
pizza[(pizza % 3 ==0) & (pizza % 4 == 1)]

array([9])